version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@{DB_HOST}:5432/${POSTGRES_DB}"

  db:
    image: postgres:latest
    container_name: laggerlogger-db-1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}