version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  postgres:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./LagerLogger/init_db.py:/app/init_db.py
    ports:
      - "5433:5432"
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  backend:
    driver: bridge